# The Site Configuration

theme: jekyll-theme-chirpy

lang: ko-KR

timezone: Asia/Seoul

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: hynrng

tagline:
  ko-KR: 반갑습니다 🔥
  en: Greetings 🔥

description: 개발일지를 포함한 다양한 일상을 다루는 블로그입니다!

url: "https://hynrng.github.io"

github:
  username: hynrng

instagram:
  username: hynrng

social:
  name: hynrng
  email: hynrng@gmail.com
  links:
    - https://github.com/hynrng
    - https://instagram.com/hynrng

webmaster_verifications:
  google: Dv7fOLMpFvAJR4CSnpDK4UEOkJ6qjz5EFpMlNRwIFwo
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-MG2GJGH0VL
  goatcounter:
    id: hynrng
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

pageviews:
  provider: goatcounter

theme_mode: # [light | dark]

cdn: "https://cdn.jsdelivr.net/gh/hynrang/hynrng.github.io-image@master"
# https://cdn.statically.io/gh/hynrang/hynrng.github.io-image@master
# https://raw.githubusercontent.com/hynrng/hynrng.github.io.resources/master

avatar: "/favicons/hynrng.webp"

social_preview_image: # string, local or CORS resources

toc: true

comments:
  provider: giscus # [disqus | utterances | giscus]
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  utterances:
    repo: hynrng/hynrng.github.io
    issue_term: pathname
  giscus:
    repo: hynrng/hynrng.github.io
    repo_id: R_kgDOH0Atrg
    category: Ideas
    category_id: DIC_kwDOH0Atrs4CeViu
    mapping: pathname
    strict: 0
    input_position: top
    lang: en
    reactions_enabled: 0

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 6

# The base URL of your site
baseurl: ""

# region 수정됨
plugins:
  - jekyll-redirect-from
  - jekyll-polyglot

# jekyll-polyglot
languages: ["ko-KR", "en"]
default_lang: "ko-KR"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false

# 태그 수 제한: _layouts/trending-tags.html
tag_limit: 10
# endregion 수정됨

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed
  sourcemap: never # jekyll-polyglot

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/