# The Site Configuration

theme: jekyll-theme-chirpy

lang: ko-KR

timezone: Asia/Seoul

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: HYNGNG

tagline: 반갑습니다 🔥

description: 개발일지를 포함한 다양한 일상을 다루는 블로그입니다! 프로그래밍, 그림, 사진 등 여러 다양한 분야에 대한 개인적인 활동을 다루고 있습니다!

url: "https://hyngng.github.io"

github:
  username: hyngng
  
instagram:
  username: hyngng_1
  
social:
  name: hyngng
  email: hyngng@gmail.com
  links:
    - https://github.com/hyngng
    - https://instagram.com/hyngng_1

webmaster_verifications:
  google: Dv7fOLMpFvAJR4CSnpDK4UEOkJ6qjz5EFpMlNRwIFwo
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: t532r1xztffviexgh17x9fkmjmesjo

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: G-XY2QYYTPGN
  goatcounter:
    id: hyngng
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

pageviews:
  provider: # goatcounter

theme_mode: # [light | dark]

cdn: "https://cdn.jsdelivr.net/gh/hyngng/hyngng.github.io.resources@master"
# https://cdn.statically.io/gh/hynrang/hyngng.github.ioresources@master
# https://cdn.jsdelivr.net/gh/hyngng/hyngng.github.io.resources@master
# https://raw.githubusercontent.com/hyngng/hyngng.github.io.resources/master

avatar: "/avatar/hyngng-white.webp"

social_preview_image: # string, local or CORS resources

toc: true

comments:
  provider: giscus
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  utterances:
    repo: hyngng/hyngng.github.io
    issue_term: pathname
  giscus:
    repo: hyngng/hyngng.github.io
    repo_id: R_kgDOH0Atrg
    category: Ideas
    category_id: DIC_kwDOH0Atrs4CeViu
    mapping: pathname
    strict: 0
    input_position: top
    lang: ko # en
    reactions_enabled: 1

assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 8

# The base URL of your site
baseurl: ""

# region 수정됨
plugins:
  - jekyll-redirect-from
# endregion 수정됨

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
