# The Site Configuration
#
# Reference
#   - Language:       http://www.lingoes.net/en/translator/langcode.htm
#   - jekyll-seo-tag: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

theme: jekyll-theme-chirpy

lang: ko-KR

timezone: Asia/Seoul

title: hynrng

tagline: 반갑습니다 🔥

description: 개발일지를 포함한 다양한 일상을 다루는 블로그입니다!

url: "https://hynrng.github.io"

github:
  username: hynrng
  
instagram:
  username: hynrng

social:
  name: hynrng
  email: hynrng@gmail.com
  links:
    - https://github.com/hynrng
    - https://instagram.com/hynrng

google_site_verification: Dv7fOLMpFvAJR4CSnpDK4UEOkJ6qjz5EFpMlNRwIFwo

# --- The end of `jekyll-seo-tag` settings ---

google_analytics:
  id: G-MG2GJGH0VL

theme_mode: # [light|dark]

# 이미지 정상 업로드 위한 주석처리
img_cdn: "https://raw.githubusercontent.com/hynrng/hynrng.github.io-image/master"
# https://cdn.jsdelivr.net/gh/hynrang/hynrng.github.io-image@master
# https://raw.githubusercontent.com/hynrng/hynrng.github.io-image/master

avatar: "/favicons/hynrng.png"

toc: true # boolean type, the global switch for TOC in posts.

comments:
  active: utterances # keeping it empty means none
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: hynrng/hynrng.github.io
    issue_term: pathname
  # Giscus options › https://giscus.app
  giscus:
    repo: hynrng/hynrng.github.io
    repo_id: R_kgDOH0Atrg
    category: Ideas
    category_id: DIC_kwDOH0Atrs4CeViu
    mapping: pathname
    input_position: top
    lang: ko  
    reactions_enabled: 0

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true

paginate: 5

baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/