import type { AstroIntegration } from 'astro';
import fs from 'node:fs';
import { getFrontmatterLang, getFrontmatterAuthor } from '../utils/frontmatter-lang';
import { normalizeLang } from '../utils/lang';
import { localePath } from '../utils/locale-segments';
import { listPostFiles } from '../utils/postFiles';
import { ALL_AUTHORS } from '../settings/authors.settings';

const RESERVED_SLUGS = ['rss.xml', 'sitemap.xml', 'index', 'rss', 'sitemap', 'favicon.ico', 'robots.txt'];
const RESERVED_AUTHOR_IDS = ['api', 'rss', 'sitemap', 'assets', 'admin', 'content', 'posts', 'authors'];

// Collects (lang, author, slug) metadata from every post.
// Routes are generated as `/${author}/${slug}` or `/${lang}/${author}/${slug}`,
// so (lang, author, slug) must be unique to avoid real route collisions.
interface PostRouteMeta {
  lang: string;
  author: string;
  slug: string;
  file: string;
}

function getPostRouteEntries(): PostRouteMeta[] {
  const entries: PostRouteMeta[] = [];
  for (const { fullPath, relativePath, slug } of listPostFiles()) {
    const raw = fs.readFileSync(fullPath, 'utf8');
    let lang: string | null;
    let author: string;
    try {
      lang = normalizeLang(getFrontmatterLang(raw) ?? '');
      author = getFrontmatterAuthor(raw);
    } catch (err) {
      throw new Error(
        `[Frontmatter Parse Error] Post "${relativePath}" has invalid frontmatter YAML.`,
        { cause: err }
      );
    }
    if (!lang) {
      throw new Error(
        `[Missing lang] Post "${relativePath}" has no frontmatter \`lang\`. ` +
        `Language is required and must be a BCP 47 language tag (e.g. ko-KR, zh-CN).`
      );
    }
    entries.push({ lang, author, slug, file: relativePath });
  }
  return entries;
}

export function validateRoutes(): AstroIntegration {
  return {
    name: 'validate-routes',
    hooks: {
      'astro:build:start': async () => {
        const entries = getPostRouteEntries();
        const seen = new Map<string, string>();
        for (const { lang, author, slug, file } of entries) {
          if (RESERVED_SLUGS.includes(slug)) {
            throw new Error(
              `[Reserved Slug Conflict] Post "${file}" uses reserved slug "${slug}". ` +
              `Reserved slugs: ${RESERVED_SLUGS.join(', ')}`
            );
          }
          // Key on the actual output path (segment + author + slug), matching real route collisions.
          const key = `${localePath(lang)}/${author}/${slug}`;
          if (seen.has(key)) {
            throw new Error(
              `[Duplicate Post Route] Route "${key}" is generated by more than one post ` +
              `("${seen.get(key)}" and "${file}"). ` +
              `Routes are keyed by (lang, author, slug).`
            );
          }
          seen.set(key, file);
        }
        for (const author of ALL_AUTHORS) {
          if (RESERVED_AUTHOR_IDS.includes(author.name)) {
            throw new Error(`[Reserved Author ID] "${author.name}" is a reserved route segment.`);
          }
        }
        console.log('[validate-routes] OK — no conflicts');
      },
    },
  };
}
