name: 'IndexNow'
on:
  schedule:
    - cron: '0 2 * * *'
    
workflow_dispatch: true

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://hynrng.github.io/sitemap'
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: 'api.indexnow.org'